name: studypulse
description: A smart student utility app for exams, calculations & productivity.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2

  connectivity_plus: ^6.0.5
  internet_connection_checker: ^1.0.0+1

  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_messaging: ^14.7.10
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.8

  google_mobile_ads: ^5.3.1
  shared_preferences: ^2.2.2
  device_info_plus: ^10.1.0

  permission_handler: ^11.3.0
  url_launcher: ^6.2.5
  app_badge_plus: ^1.2.0

  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/quotes.txt
    - assets/percentage.png
    - assets/cgpa.png
    - assets/exam.png
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
